ext-src/php_swoole.lo: /home/natanyel/Documentos/swoole-src/ext-src/php_swoole.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/php_swoole.cc -o ext-src/php_swoole.lo 
ext-src/php_swoole_cxx.lo: /home/natanyel/Documentos/swoole-src/ext-src/php_swoole_cxx.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/php_swoole_cxx.cc -o ext-src/php_swoole_cxx.lo 
ext-src/swoole_admin_server.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_admin_server.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_admin_server.cc -o ext-src/swoole_admin_server.lo 
ext-src/swoole_async_coro.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_async_coro.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_async_coro.cc -o ext-src/swoole_async_coro.lo 
ext-src/swoole_atomic.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_atomic.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_atomic.cc -o ext-src/swoole_atomic.lo 
ext-src/swoole_channel_coro.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_channel_coro.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_channel_coro.cc -o ext-src/swoole_channel_coro.lo 
ext-src/swoole_client.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_client.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_client.cc -o ext-src/swoole_client.lo 
ext-src/swoole_client_coro.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_client_coro.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_client_coro.cc -o ext-src/swoole_client_coro.lo 
ext-src/swoole_coroutine.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_coroutine.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_coroutine.cc -o ext-src/swoole_coroutine.lo 
ext-src/swoole_coroutine_scheduler.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_coroutine_scheduler.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_coroutine_scheduler.cc -o ext-src/swoole_coroutine_scheduler.lo 
ext-src/swoole_coroutine_system.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_coroutine_system.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_coroutine_system.cc -o ext-src/swoole_coroutine_system.lo 
ext-src/swoole_curl.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_curl.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_curl.cc -o ext-src/swoole_curl.lo 
ext-src/swoole_event.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_event.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_event.cc -o ext-src/swoole_event.lo 
ext-src/swoole_http2_client_coro.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_http2_client_coro.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_http2_client_coro.cc -o ext-src/swoole_http2_client_coro.lo 
ext-src/swoole_http2_server.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_http2_server.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_http2_server.cc -o ext-src/swoole_http2_server.lo 
ext-src/swoole_http_client_coro.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_http_client_coro.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_http_client_coro.cc -o ext-src/swoole_http_client_coro.lo 
ext-src/swoole_http_request.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_http_request.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_http_request.cc -o ext-src/swoole_http_request.lo 
ext-src/swoole_http_response.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_http_response.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_http_response.cc -o ext-src/swoole_http_response.lo 
ext-src/swoole_http_server.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_http_server.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_http_server.cc -o ext-src/swoole_http_server.lo 
ext-src/swoole_http_server_coro.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_http_server_coro.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_http_server_coro.cc -o ext-src/swoole_http_server_coro.lo 
ext-src/swoole_lock.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_lock.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_lock.cc -o ext-src/swoole_lock.lo 
ext-src/swoole_mysql_coro.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_mysql_coro.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_mysql_coro.cc -o ext-src/swoole_mysql_coro.lo 
ext-src/swoole_mysql_proto.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_mysql_proto.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_mysql_proto.cc -o ext-src/swoole_mysql_proto.lo 
ext-src/swoole_name_resolver.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_name_resolver.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_name_resolver.cc -o ext-src/swoole_name_resolver.lo 
ext-src/swoole_postgresql_coro.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_postgresql_coro.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_postgresql_coro.cc -o ext-src/swoole_postgresql_coro.lo 
ext-src/swoole_process.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_process.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_process.cc -o ext-src/swoole_process.lo 
ext-src/swoole_process_pool.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_process_pool.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_process_pool.cc -o ext-src/swoole_process_pool.lo 
ext-src/swoole_redis_coro.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_redis_coro.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_redis_coro.cc -o ext-src/swoole_redis_coro.lo 
ext-src/swoole_redis_server.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_redis_server.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_redis_server.cc -o ext-src/swoole_redis_server.lo 
ext-src/swoole_runtime.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_runtime.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_runtime.cc -o ext-src/swoole_runtime.lo 
ext-src/swoole_server.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_server.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_server.cc -o ext-src/swoole_server.lo 
ext-src/swoole_server_port.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_server_port.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_server_port.cc -o ext-src/swoole_server_port.lo 
ext-src/swoole_socket_coro.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_socket_coro.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_socket_coro.cc -o ext-src/swoole_socket_coro.lo 
ext-src/swoole_table.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_table.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_table.cc -o ext-src/swoole_table.lo 
ext-src/swoole_timer.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_timer.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_timer.cc -o ext-src/swoole_timer.lo 
ext-src/swoole_websocket_server.lo: /home/natanyel/Documentos/swoole-src/ext-src/swoole_websocket_server.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/ext-src/swoole_websocket_server.cc -o ext-src/swoole_websocket_server.lo 
src/core/base.lo: /home/natanyel/Documentos/swoole-src/src/core/base.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/core/base.cc -o src/core/base.lo 
src/core/channel.lo: /home/natanyel/Documentos/swoole-src/src/core/channel.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/core/channel.cc -o src/core/channel.lo 
src/core/crc32.lo: /home/natanyel/Documentos/swoole-src/src/core/crc32.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/core/crc32.cc -o src/core/crc32.lo 
src/core/error.lo: /home/natanyel/Documentos/swoole-src/src/core/error.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/core/error.cc -o src/core/error.lo 
src/core/heap.lo: /home/natanyel/Documentos/swoole-src/src/core/heap.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/core/heap.cc -o src/core/heap.lo 
src/core/log.lo: /home/natanyel/Documentos/swoole-src/src/core/log.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/core/log.cc -o src/core/log.lo 
src/core/string.lo: /home/natanyel/Documentos/swoole-src/src/core/string.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/core/string.cc -o src/core/string.lo 
src/core/timer.lo: /home/natanyel/Documentos/swoole-src/src/core/timer.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/core/timer.cc -o src/core/timer.lo 
src/coroutine/base.lo: /home/natanyel/Documentos/swoole-src/src/coroutine/base.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/coroutine/base.cc -o src/coroutine/base.lo 
src/coroutine/channel.lo: /home/natanyel/Documentos/swoole-src/src/coroutine/channel.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/coroutine/channel.cc -o src/coroutine/channel.lo 
src/coroutine/context.lo: /home/natanyel/Documentos/swoole-src/src/coroutine/context.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/coroutine/context.cc -o src/coroutine/context.lo 
src/coroutine/file_lock.lo: /home/natanyel/Documentos/swoole-src/src/coroutine/file_lock.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/coroutine/file_lock.cc -o src/coroutine/file_lock.lo 
src/coroutine/hook.lo: /home/natanyel/Documentos/swoole-src/src/coroutine/hook.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/coroutine/hook.cc -o src/coroutine/hook.lo 
src/coroutine/socket.lo: /home/natanyel/Documentos/swoole-src/src/coroutine/socket.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/coroutine/socket.cc -o src/coroutine/socket.lo 
src/coroutine/system.lo: /home/natanyel/Documentos/swoole-src/src/coroutine/system.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/coroutine/system.cc -o src/coroutine/system.lo 
src/coroutine/thread_context.lo: /home/natanyel/Documentos/swoole-src/src/coroutine/thread_context.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/coroutine/thread_context.cc -o src/coroutine/thread_context.lo 
src/lock/mutex.lo: /home/natanyel/Documentos/swoole-src/src/lock/mutex.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/lock/mutex.cc -o src/lock/mutex.lo 
src/lock/rw_lock.lo: /home/natanyel/Documentos/swoole-src/src/lock/rw_lock.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/lock/rw_lock.cc -o src/lock/rw_lock.lo 
src/lock/spin_lock.lo: /home/natanyel/Documentos/swoole-src/src/lock/spin_lock.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/lock/spin_lock.cc -o src/lock/spin_lock.lo 
src/memory/buffer.lo: /home/natanyel/Documentos/swoole-src/src/memory/buffer.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/memory/buffer.cc -o src/memory/buffer.lo 
src/memory/fixed_pool.lo: /home/natanyel/Documentos/swoole-src/src/memory/fixed_pool.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/memory/fixed_pool.cc -o src/memory/fixed_pool.lo 
src/memory/global_memory.lo: /home/natanyel/Documentos/swoole-src/src/memory/global_memory.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/memory/global_memory.cc -o src/memory/global_memory.lo 
src/memory/ring_buffer.lo: /home/natanyel/Documentos/swoole-src/src/memory/ring_buffer.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/memory/ring_buffer.cc -o src/memory/ring_buffer.lo 
src/memory/shared_memory.lo: /home/natanyel/Documentos/swoole-src/src/memory/shared_memory.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/memory/shared_memory.cc -o src/memory/shared_memory.lo 
src/memory/table.lo: /home/natanyel/Documentos/swoole-src/src/memory/table.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/memory/table.cc -o src/memory/table.lo 
src/network/address.lo: /home/natanyel/Documentos/swoole-src/src/network/address.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/network/address.cc -o src/network/address.lo 
src/network/client.lo: /home/natanyel/Documentos/swoole-src/src/network/client.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/network/client.cc -o src/network/client.lo 
src/network/dns.lo: /home/natanyel/Documentos/swoole-src/src/network/dns.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/network/dns.cc -o src/network/dns.lo 
src/network/socket.lo: /home/natanyel/Documentos/swoole-src/src/network/socket.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/network/socket.cc -o src/network/socket.lo 
src/network/stream.lo: /home/natanyel/Documentos/swoole-src/src/network/stream.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/network/stream.cc -o src/network/stream.lo 
src/os/async_thread.lo: /home/natanyel/Documentos/swoole-src/src/os/async_thread.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/os/async_thread.cc -o src/os/async_thread.lo 
src/os/base.lo: /home/natanyel/Documentos/swoole-src/src/os/base.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/os/base.cc -o src/os/base.lo 
src/os/file.lo: /home/natanyel/Documentos/swoole-src/src/os/file.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/os/file.cc -o src/os/file.lo 
src/os/msg_queue.lo: /home/natanyel/Documentos/swoole-src/src/os/msg_queue.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/os/msg_queue.cc -o src/os/msg_queue.lo 
src/os/pipe.lo: /home/natanyel/Documentos/swoole-src/src/os/pipe.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/os/pipe.cc -o src/os/pipe.lo 
src/os/process_pool.lo: /home/natanyel/Documentos/swoole-src/src/os/process_pool.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/os/process_pool.cc -o src/os/process_pool.lo 
src/os/sendfile.lo: /home/natanyel/Documentos/swoole-src/src/os/sendfile.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/os/sendfile.cc -o src/os/sendfile.lo 
src/os/signal.lo: /home/natanyel/Documentos/swoole-src/src/os/signal.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/os/signal.cc -o src/os/signal.lo 
src/os/timer.lo: /home/natanyel/Documentos/swoole-src/src/os/timer.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/os/timer.cc -o src/os/timer.lo 
src/os/unix_socket.lo: /home/natanyel/Documentos/swoole-src/src/os/unix_socket.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/os/unix_socket.cc -o src/os/unix_socket.lo 
src/os/wait.lo: /home/natanyel/Documentos/swoole-src/src/os/wait.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/os/wait.cc -o src/os/wait.lo 
src/protocol/base.lo: /home/natanyel/Documentos/swoole-src/src/protocol/base.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/protocol/base.cc -o src/protocol/base.lo 
src/protocol/base64.lo: /home/natanyel/Documentos/swoole-src/src/protocol/base64.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/protocol/base64.cc -o src/protocol/base64.lo 
src/protocol/dtls.lo: /home/natanyel/Documentos/swoole-src/src/protocol/dtls.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/protocol/dtls.cc -o src/protocol/dtls.lo 
src/protocol/http.lo: /home/natanyel/Documentos/swoole-src/src/protocol/http.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/protocol/http.cc -o src/protocol/http.lo 
src/protocol/http2.lo: /home/natanyel/Documentos/swoole-src/src/protocol/http2.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/protocol/http2.cc -o src/protocol/http2.lo 
src/protocol/mime_type.lo: /home/natanyel/Documentos/swoole-src/src/protocol/mime_type.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/protocol/mime_type.cc -o src/protocol/mime_type.lo 
src/protocol/mqtt.lo: /home/natanyel/Documentos/swoole-src/src/protocol/mqtt.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/protocol/mqtt.cc -o src/protocol/mqtt.lo 
src/protocol/redis.lo: /home/natanyel/Documentos/swoole-src/src/protocol/redis.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/protocol/redis.cc -o src/protocol/redis.lo 
src/protocol/socks5.lo: /home/natanyel/Documentos/swoole-src/src/protocol/socks5.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/protocol/socks5.cc -o src/protocol/socks5.lo 
src/protocol/ssl.lo: /home/natanyel/Documentos/swoole-src/src/protocol/ssl.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/protocol/ssl.cc -o src/protocol/ssl.lo 
src/protocol/websocket.lo: /home/natanyel/Documentos/swoole-src/src/protocol/websocket.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/protocol/websocket.cc -o src/protocol/websocket.lo 
src/reactor/base.lo: /home/natanyel/Documentos/swoole-src/src/reactor/base.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/reactor/base.cc -o src/reactor/base.lo 
src/reactor/epoll.lo: /home/natanyel/Documentos/swoole-src/src/reactor/epoll.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/reactor/epoll.cc -o src/reactor/epoll.lo 
src/reactor/kqueue.lo: /home/natanyel/Documentos/swoole-src/src/reactor/kqueue.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/reactor/kqueue.cc -o src/reactor/kqueue.lo 
src/reactor/poll.lo: /home/natanyel/Documentos/swoole-src/src/reactor/poll.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/reactor/poll.cc -o src/reactor/poll.lo 
src/reactor/select.lo: /home/natanyel/Documentos/swoole-src/src/reactor/select.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/reactor/select.cc -o src/reactor/select.lo 
src/server/base.lo: /home/natanyel/Documentos/swoole-src/src/server/base.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/server/base.cc -o src/server/base.lo 
src/server/manager.lo: /home/natanyel/Documentos/swoole-src/src/server/manager.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/server/manager.cc -o src/server/manager.lo 
src/server/master.lo: /home/natanyel/Documentos/swoole-src/src/server/master.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/server/master.cc -o src/server/master.lo 
src/server/message_bus.lo: /home/natanyel/Documentos/swoole-src/src/server/message_bus.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/server/message_bus.cc -o src/server/message_bus.lo 
src/server/port.lo: /home/natanyel/Documentos/swoole-src/src/server/port.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/server/port.cc -o src/server/port.lo 
src/server/process.lo: /home/natanyel/Documentos/swoole-src/src/server/process.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/server/process.cc -o src/server/process.lo 
src/server/reactor_process.lo: /home/natanyel/Documentos/swoole-src/src/server/reactor_process.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/server/reactor_process.cc -o src/server/reactor_process.lo 
src/server/reactor_thread.lo: /home/natanyel/Documentos/swoole-src/src/server/reactor_thread.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/server/reactor_thread.cc -o src/server/reactor_thread.lo 
src/server/static_handler.lo: /home/natanyel/Documentos/swoole-src/src/server/static_handler.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/server/static_handler.cc -o src/server/static_handler.lo 
src/server/task_worker.lo: /home/natanyel/Documentos/swoole-src/src/server/task_worker.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/server/task_worker.cc -o src/server/task_worker.lo 
src/server/worker.lo: /home/natanyel/Documentos/swoole-src/src/server/worker.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/server/worker.cc -o src/server/worker.lo 
src/wrapper/event.lo: /home/natanyel/Documentos/swoole-src/src/wrapper/event.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/wrapper/event.cc -o src/wrapper/event.lo 
src/wrapper/timer.lo: /home/natanyel/Documentos/swoole-src/src/wrapper/timer.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/src/wrapper/timer.cc -o src/wrapper/timer.lo 
thirdparty/php/curl/interface.lo: /home/natanyel/Documentos/swoole-src/thirdparty/php/curl/interface.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/php/curl/interface.cc -o thirdparty/php/curl/interface.lo 
thirdparty/php/curl/multi.lo: /home/natanyel/Documentos/swoole-src/thirdparty/php/curl/multi.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/php/curl/multi.cc -o thirdparty/php/curl/multi.lo 
thirdparty/php/sockets/multicast.lo: /home/natanyel/Documentos/swoole-src/thirdparty/php/sockets/multicast.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/php/sockets/multicast.cc -o thirdparty/php/sockets/multicast.lo 
thirdparty/php/sockets/sendrecvmsg.lo: /home/natanyel/Documentos/swoole-src/thirdparty/php/sockets/sendrecvmsg.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/php/sockets/sendrecvmsg.cc -o thirdparty/php/sockets/sendrecvmsg.lo 
thirdparty/php/sockets/conversions.lo: /home/natanyel/Documentos/swoole-src/thirdparty/php/sockets/conversions.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/php/sockets/conversions.cc -o thirdparty/php/sockets/conversions.lo 
thirdparty/php/sockets/sockaddr_conv.lo: /home/natanyel/Documentos/swoole-src/thirdparty/php/sockets/sockaddr_conv.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/php/sockets/sockaddr_conv.cc -o thirdparty/php/sockets/sockaddr_conv.lo 
thirdparty/php/standard/var_decoder.lo: /home/natanyel/Documentos/swoole-src/thirdparty/php/standard/var_decoder.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/php/standard/var_decoder.cc -o thirdparty/php/standard/var_decoder.lo 
thirdparty/php/standard/proc_open.lo: /home/natanyel/Documentos/swoole-src/thirdparty/php/standard/proc_open.cc
	$(LIBTOOL) --mode=compile $(CXX) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/php/standard/proc_open.cc -o thirdparty/php/standard/proc_open.lo 
thirdparty/swoole_http_parser.lo: /home/natanyel/Documentos/swoole-src/thirdparty/swoole_http_parser.c
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/swoole_http_parser.c -o thirdparty/swoole_http_parser.lo 
thirdparty/multipart_parser.lo: /home/natanyel/Documentos/swoole-src/thirdparty/multipart_parser.c
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/multipart_parser.c -o thirdparty/multipart_parser.lo 
thirdparty/hiredis/hiredis.lo: /home/natanyel/Documentos/swoole-src/thirdparty/hiredis/hiredis.c
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/hiredis/hiredis.c -o thirdparty/hiredis/hiredis.lo 
thirdparty/hiredis/alloc.lo: /home/natanyel/Documentos/swoole-src/thirdparty/hiredis/alloc.c
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/hiredis/alloc.c -o thirdparty/hiredis/alloc.lo 
thirdparty/hiredis/net.lo: /home/natanyel/Documentos/swoole-src/thirdparty/hiredis/net.c
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/hiredis/net.c -o thirdparty/hiredis/net.lo 
thirdparty/hiredis/read.lo: /home/natanyel/Documentos/swoole-src/thirdparty/hiredis/read.c
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/hiredis/read.c -o thirdparty/hiredis/read.lo 
thirdparty/hiredis/sds.lo: /home/natanyel/Documentos/swoole-src/thirdparty/hiredis/sds.c
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/hiredis/sds.c -o thirdparty/hiredis/sds.lo 
thirdparty/nghttp2/nghttp2_hd.lo: /home/natanyel/Documentos/swoole-src/thirdparty/nghttp2/nghttp2_hd.c
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/nghttp2/nghttp2_hd.c -o thirdparty/nghttp2/nghttp2_hd.lo 
thirdparty/nghttp2/nghttp2_rcbuf.lo: /home/natanyel/Documentos/swoole-src/thirdparty/nghttp2/nghttp2_rcbuf.c
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/nghttp2/nghttp2_rcbuf.c -o thirdparty/nghttp2/nghttp2_rcbuf.lo 
thirdparty/nghttp2/nghttp2_helper.lo: /home/natanyel/Documentos/swoole-src/thirdparty/nghttp2/nghttp2_helper.c
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/nghttp2/nghttp2_helper.c -o thirdparty/nghttp2/nghttp2_helper.lo 
thirdparty/nghttp2/nghttp2_buf.lo: /home/natanyel/Documentos/swoole-src/thirdparty/nghttp2/nghttp2_buf.c
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/nghttp2/nghttp2_buf.c -o thirdparty/nghttp2/nghttp2_buf.lo 
thirdparty/nghttp2/nghttp2_mem.lo: /home/natanyel/Documentos/swoole-src/thirdparty/nghttp2/nghttp2_mem.c
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/nghttp2/nghttp2_mem.c -o thirdparty/nghttp2/nghttp2_mem.lo 
thirdparty/nghttp2/nghttp2_hd_huffman.lo: /home/natanyel/Documentos/swoole-src/thirdparty/nghttp2/nghttp2_hd_huffman.c
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/nghttp2/nghttp2_hd_huffman.c -o thirdparty/nghttp2/nghttp2_hd_huffman.lo 
thirdparty/nghttp2/nghttp2_hd_huffman_data.lo: /home/natanyel/Documentos/swoole-src/thirdparty/nghttp2/nghttp2_hd_huffman_data.c
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/nghttp2/nghttp2_hd_huffman_data.c -o thirdparty/nghttp2/nghttp2_hd_huffman_data.lo 
thirdparty/boost/asm/make_x86_64_sysv_elf_gas.lo: /home/natanyel/Documentos/swoole-src/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S -o thirdparty/boost/asm/make_x86_64_sysv_elf_gas.lo 
thirdparty/boost/asm/jump_x86_64_sysv_elf_gas.lo: /home/natanyel/Documentos/swoole-src/thirdparty/boost/asm/jump_x86_64_sysv_elf_gas.S
	$(LIBTOOL) --mode=compile $(CC) -I. -I/home/natanyel/Documentos/swoole-src $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DENABLE_PHP_SWOOLE -c /home/natanyel/Documentos/swoole-src/thirdparty/boost/asm/jump_x86_64_sysv_elf_gas.S -o thirdparty/boost/asm/jump_x86_64_sysv_elf_gas.lo 
$(phplibdir)/swoole.la: ./swoole.la
	$(LIBTOOL) --mode=install cp ./swoole.la $(phplibdir)

./swoole.la: $(shared_objects_swoole) $(SWOOLE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CXX) -shared $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_swoole) $(SWOOLE_SHARED_LIBADD)

